# -*- coding: utf-8 -*-
"""EDA_Assignment_Breast_Cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3eb_xuMDvn4Y-RjgsaI68_kvn0Uf64X

# Dataset Selection

The dataset used for this is"Breast Cancer Diagnosis"
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Data Loading and Cleaning"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Breast Cancer Diagnosis.csv")
df.head()

"""Descriptive Statistics and Exploration"""

print(df.info())

print(df.describe())

df = df.dropna()

df.rename(columns={'diagnosis': 'Diagnosis'}, inplace=True)

df['Diagnosis'] = df['Diagnosis'].astype('category')

df.describe()

df['Diagnosis'].value_counts()

num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include='category').columns

df[num_cols].mean()
df[num_cols].median()
df[num_cols].mode()
df[num_cols].std()

"""Data Visualization"""

plt.figure(figsize=(8,5))
sns.boxplot(x=df['radius_mean'])
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['radius_mean'], kde=True)
plt.title("Distribution of Radius Mean")
plt.show()

sns.scatterplot(x='radius_mean', y='texture_mean', hue='Diagnosis', data=df)
plt.show()

sns.violinplot(x='Diagnosis', y='radius_mean', data=df)
plt.show()

sns.histplot(df['area_mean'], kde=True)
plt.show()